### ISSUE TITLE
ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by unravelstorm** [529324416/UnityCommandLineInterface#1]
我在使用上下箭头获取历史命令的时候（尤其是下箭头），会报集合下标溢出。
`ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <834b2ded5dad441e8c7a4287897d63c7>:0)
RedSaw.CommandLineInterface.InputHistory.get_Next () (at Assets/CommandLine/Scripts/Core/ConsoleSystem.cs:43)
RedSaw.CommandLineInterface.Console.Update () (at Assets/CommandLine/Scripts/Core/ConsoleSystem.cs:233)
RedSaw.CommandLineInterface.UnityImpl.GameConsole.Update () (at Assets/CommandLine/Scripts/UnityImpl/GameConsole.cs:53)`

对应位置：ConsoleSystem.cs文件中
![image](https://github.com/529324416/UnityCommandLineInterface/assets/38400221/4349b23a-214b-4f9b-9831-0b283165c575)

**Comment by 529324416** [comment]
Ok，我看见了，主要是因为输入历史既可以上翻也可以下翻，所以处于边界的时候转向会有问题，目前已经修复了。
![图片](https://github.com/529324416/UnityCommandLineInterface/assets/30776995/8332c8b5-4704-4c78-aab8-a59cc6488d8b)

**Comment by unravelstorm** [comment]
> Ok，我看见了，主要是因为输入历史既可以上翻也可以下翻，所以处于边界的时候转向会有问题，目前已经修复了。 ![图片](https://private-user-images.githubusercontent.com/30776995/294155509-8332c8b5-4704-4c78-aab8-a59cc6488d8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNjYxODIsIm5iZiI6MTcwNDM2NTg4MiwicGF0aCI6Ii8zMDc3Njk5NS8yOTQxNTU1MDktODMzMmM4YjUtNDcwNC00Yzc4LWFhYjgtYTU5Y2M2NDg4ZDhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDEwNTgwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiZjNhMTczNGEzZWEyZmJkYWNhMmZkYzM4ZWFjYjRlMzQ0NzFiNTcwNzQ2YjZkZTA4NjhkMGU4NGJhZTM3OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wAeuvWJBz0uDnX7TQ7CBIXaSK3bNf4a4RL3tXjqPbV8)

可以，这效率，issue关了
