### ISSUE TITLE
请问一下项目支持的Unity版本范围是？谢谢~

### ISSUE THREAD

**Issue by sdyby2006** [529324416/UnityCommandLineInterface#2]
请问一下项目支持的Unity版本范围是？谢谢~

**Comment by 529324416** [comment]
支持2018.03以及更新的所有版本的Unity，它的内核模块与Unity是完全解耦的，上层UI实现暂时只采用了旧版Text，TMP版本的UI还没有实现，可以手动实现，也可以等后续的更新。

**Comment by 529324416** [comment]
目前支持的版本已经更新到文档了

**Comment by sdyby2006** [comment]
> 目前支持的版本已经更新到文档了

好的，谢谢~~~
